version: '3.8'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - /usr/src/app/src/node_modules
    command: npm run start
    depends_on:
        - placeholder-api

  placeholder-api:
    build: ./placeholder-api
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./placeholder-api/src:/usr/src/app/src
    command: npm run dev

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  nginx:
    image: nginx:alpine
    ports:
      - 1234:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - placeholder-api
      - redis