version: '3.8'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm run start

  placeholder-api:
    build: ./placeholder-api
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./placeholder-api/src:/usr/src/app/src
    command: npm run dev

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  nginx:
    image: nginx
    ports:
      - 1234:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  # mongo:
  #   image: mongo
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=nav
  #     - MONGO_INITDB_ROOT_PASSWORD=1234